amcl:
  ros__parameters:
    use_sim_time: false
    lambda_short: 0.1
    max_beams: 30
    min_particles: 500
    max_particles: 2000
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.1
    z_hit: 0.5
    z_short: 0.05
    z_max: 0.05
    z_rand: 0.5
    sigma_hit: 0.2
    laser_likelihood_max_dist: 2.0
    update_min_d: 0.2
    update_min_a: 0.2
    resample_interval: 1
    transform_tolerance: 1.0
    recovery_alpha_slow: 0.001
    recovery_alpha_fast: 0.1
    tf_broadcast: true
    odom_frame_id: "odom"
    base_frame_id: ""
    scan_topic: "scan"
    map_topic: "map"
    use_map_topic: true
    first_map_only: true
    gui_publish_rate: 10.0
    save_pose_rate: 0.5


